CREATE INDEX DURATION_SORT ON ICATLOG(DURATION,USER_ID);
CREATE INDEX LOGTIME_SORT ON ICATLOG(LOGTIME, USER_ID);
CREATE INDEX DURATION_OPERATION_SORT ON ICATLOG(DURATION,OPERATION);
CREATE INDEX DURATION_OPERATION_LOGTIME ON ICATLOG(OPERATION,LOGTIME);
