#!/usr/bin/env python
from setup_utils import *
import os
import socket

# icat.server

def uninstall():    
    app = actions.getAppName("dashboard")
    if app: actions.undeploy(app)
    actions.unregisterDB("dashboard")
    actions._asadmin("set server.jms-service.type=EMBEDDED")
    actions._asadmin("set configs.config.server-config.jms-service.jms-host.default_JMS_host.host=localhost")


    
actions, arg, props = getActions("dashboard-setup.properties", ["db.vendor", "db.driver", "db.url", "db.username", "db.password","ids.address"])


prop_name = "dashboard.properties"
prop_list = []

if arg in ["CONFIGURE", "INSTALL"]: actions.configure(prop_name, prop_list) 
dashboardProperties = getProperties(prop_name, prop_list)


if arg in ["CONFIGURE", "INSTALL"]:
    
    actions.checkNoErrors()
	

if arg == "INSTALL": 
    
    actions.installFile("dashboard.properties")
    
    
    try: 
                  
        uninstall()
        actions.registerDB("dashboard", props["db.vendor"], props["db.driver"], props["db.url"], props["db.username"], props["db.password"])
	actions._asadmin("set server.jms-service.type=REMOTE")
	actions._asadmin("set configs.config.server-config.jms-service.jms-host.default_JMS_host.host="+props["ids.address"])
        actions._asadmin("restart-domain")
	actions.deploy()   
        
    except Exception, e:
        abort(str(e))
                
if arg == "UNINSTALL":        
    actions.removeFile(prop_name)
    
    
    try:
        uninstall()
        
    except Exception, e:
        abort(str(e))       
